apiVersion: v1
kind: Service
metadata:
  name: {{ include "ent-openai-lambots-api-chart.fullname" . }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    {{- include "ent-openai-lambots-api-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "ent-openai-lambots-api-chart.selectorLabels" . | nindent 4 }}
