customer_names_case_insensitive = [
    "Micron",
    "TSMC, Fab 12",
    "TSMC,Fab12",
    "TSMC,",
    "Samsung",
    "Sony",
    "YMTC",
    "TSMC",
    "UMC 300mm",
    "UMC300mm",
    "UMC",
    "Inotera",
    "CSM",
    "Samsung G2 (L15/16)",
    "SamsungG2(L15/16)",
    "Intel",
    "Micron (Boise)",
    "Micron(Boise)",
    "IBM (NY)",
    "IBM(NY)",
    "IBM",
    "Toshiba",
    "IBM (VT)",
    "IBM(VT)",
    "Toshiba Yokkaichi",
    "ToshibaYokkaichi",
    "GlobalFoundries",
    "Hynix (Wuxi China)",
    "Hynix(WuxiChina)",
    "Hynix",
    "TI",
    "AMD",
    "SK hynix",
    "SKhynix",
    "SK",
    "ST Agrate",
    "STAgrate",
    "ST",
    "Chandler",
    "Tech Semi, Singapore",
    "TechSemi,Singapore",
    "Tech",
    "Samsung (Austin)",
    "Samsung(Austin)",
    "Altis",
    "Intel (Ireland)",
    "Intel(Ireland)",
    "SMIC",
    "Foliage",
    "Hynix (Korea)",
    "Hynix(Korea)",
    "Intel (OR)",
    "Intel(OR)",
    "External ID",
    "ExternalID",
    "External",
    "Nanya",
    "Philips (NY)",
    "Philips(NY)",
    "Philips",
    "Winbond 300mm",
    "Winbond300mm",
    "Winbond",
    "Samsung (Korea)",
    "Samsung(Korea)",
    "Intel (NM)",
    "Intel(NM)",
    "TSMC 200mm",
    "TSMC200mm",
    "IMFT",
    "NEC Yamagata",
    "NECYamagata",
    "NEC",
    "Silterra Malaysia",
    "SilterraMalaysia",
    "Silterra",
    "Fujitsu Mie",
    "FujitsuMie",
    "Fujitsu",
    "Global Foundries Fab1, Dresden",
    "GlobalFoundriesFab1,Dresden",
    "Global",
    "Infineon Dresden",
    "InfineonDresden",
    "Infineon",
    "Vanguard",
    "Promos",
    "Panasoinc, Uozu",
    "Panasoinc,Uozu",
    "Panasoinc,",
    "Infineon Richmond",
    "InfineonRichmond",
    "ST Rousset",
    "STRousset",
    "Crolles 2",
    "Crolles2",
    "Crolles",
    "Lucent (FL)",
    "Lucent(FL)",
    "Lucent",
    "Seki Technotron",
    "SekiTechnotron",
    "Seki",
    "Motorola",
    "SK Hynix",
    "SKHynix",
    "UMCi, Singapore",
    "UMCi,Singapore",
    "UMCi,",
    "Sematech",
    "Qimonda Dresden",
    "QimondaDresden",
    "Qimonda",
    "Intel (AZ)",
    "Intel(AZ)",
    "Micron Fab 6 (VA)",
    "MicronFab6(VA)",
    "NEC Sagamihara",
    "NECSagamihara",
    "AMS",
    "IBM Essonnes",
    "IBMEssonnes",
    "SHLMC",
    "Global Foundries Fab8, New York",
    "GlobalFoundriesFab8,NewYork",
    "NEC Yamaguchi",
    "NECYamaguchi",
    "Renesas",
    "Conexant",
    "Elpida",
    "ST Catania",
    "STCatania",
    "TSMC, Fab 14",
    "TSMC,Fab14",
    "Panasonic, Arai",
    "Panasonic,Arai",
    "Panasonic,",
    "DEC",
    "Canon",
    "Analog Devices",
    "AnalogDevices",
    "Analog",
    "Macronix",
    "National Semi Santa Clara",
    "NationalSemiSantaClara",
    "National",
    "Huali",
    "TSMC, Fab 15",
    "TSMC,Fab15",
    "Spansion Fab25",
    "SpansionFab25",
    "Spansion",
    "NSC",
    "Agere",
    "Micrus",
    "NEC Kyushu",
    "NECKyushu",
    "ATMEL",
    "LSI Logic",
    "LSILogic",
    "LSI",
    "Micron IMFS Fab10, Singapore",
    "MicronIMFSFab10,Singapore",
    "HSNL",
    "SPIL",
    "SMP",
    "Anam",
    "Qimonda Richmond",
    "QimondaRichmond",
    "Powerchip",
    "Tower Semiconductor",
    "TowerSemiconductor",
    "Tower",
    "1st Silicon, Malaysia",
    "1stSilicon,Malaysia",
    "1st",
    "MEC Tonami",
    "MECTonami",
    "MEC",
    "RDC, Mindteck Ltd., India",
    "RDC,MindteckLtd.,India",
    "RDC,",
    "Hitachi",
    "FASL",
    "Hynix (US)",
    "Hynix(US)",
    "National Semi Arlington",
    "NationalSemiArlington",
    "Intel (CA)",
    "Intel(CA)",
    "UMC 200mm",
    "UMC200mm",
    "Fujitsu, Gresham, OR",
    "Fujitsu,Gresham,OR",
    "Fujitsu,",
    "SSMC Singapore Fab1",
    "SSMCSingaporeFab1",
    "SSMC",
    "Micrel",
    "Cypress",
    "NEC Roseville",
    "NECRoseville",
    "Toshiba Iwate",
    "ToshibaIwate",
    "Spansion LLC",
    "SpansionLLC",
    "Bosch",
    "White Oaks",
    "WhiteOaks",
    "White",
    "WaferTech",
    "Yamaha",
    "HP",
    "StatsChipPac",
    "IDT (OR)",
    "IDT(OR)",
    "IDT",
    "Samsung Quality",
    "SamsungQuality",
    "SIMEC Dresden Germany",
    "SIMECDresdenGermany",
    "SIMEC",
    "Fairchild SPOR",
    "FairchildSPOR",
    "Fairchild",
    "ESM Wales",
    "ESMWales",
    "ESM",
    "Mitsubishi",
    "SMST, Sindelfingen Germany",
    "SMST,SindelfingenGermany",
    "SMST,",
    "Rockwell, Newport Beach",
    "Rockwell,NewportBeach",
    "Rockwell,",
    "Austria Microsystems, Graz",
    "AustriaMicrosystems,Graz",
    "Austria",
    "Fujitsu Iwate",
    "FujitsuIwate",
    "ASE",
    "OMRON Yasu",
    "OMRONYasu",
    "OMRON",
    "Microchip",
    "TSMC R&D",
    "TSMCR&D",
    "National Semi Minnesota",
    "NationalSemiMinnesota",
    "Harris",
    "TB 10",
    "TB10",
    "TB",
    "Phillips Nijmegen",
    "PhillipsNijmegen",
    "Phillips",
    "Fujitsu Wakamatsu",
    "FujitsuWakamatsu",
    "International Rectifier Newport",
    "InternationalRectifierNewport",
    "International",
    "Honeywell (MIN)",
    "Honeywell(MIN)",
    "Honeywell",
    "USMC",
    "Maxim",
    "Micro-Rel",
    "Selete",
    "AMI",
    "Rexchip",
    "NCR (CO)",
    "NCR(CO)",
    "NCR",
    "Sharp Fukuyama",
    "SharpFukuyama",
    "Sharp",
    "Micronas GmbH",
    "MicronasGmbH",
    "Micronas",
    "Toshiba Oita",
    "ToshibaOita",
    "Dieter Dornisch",
    "DieterDornisch",
    "Dieter",
    "Lucent (Madrid)",
    "Lucent(Madrid)",
    "International Sematech",
    "InternationalSematech",
    "Panasonic",
    "Sanyo",
    "Nittetsu",
    "Spansion SDC",
    "SpansionSDC",
    "Fuji Film",
    "FujiFilm",
    "Fuji",
    "Global Foundries Fab7, Singapore",
    "GlobalFoundriesFab7,Singapore",
    "Oki Hachioji",
    "OkiHachioji",
    "Oki",
    "Trecenti Technologies",
    "TrecentiTechnologies",
    "Trecenti",
    "Infineon Regensburg",
    "InfineonRegensburg",
    "HNS Singapore",
    "HNSSingapore",
    "HNS",
    "Jazz Semiconductor",
    "JazzSemiconductor",
    "Jazz",
    "IC Works",
    "ICWorks",
    "IC",
    "Freescale",
    "CSP",
    "UTEK",
    "SGS-Thomson",
    "Panasonic, Tonami",
    "Panasonic,Tonami",
    "VTC, Inc.",
    "VTC,Inc.",
    "VTC,",
    "BCD TB5",
    "BCDTB5",
    "BCD",
    "CMI",
    "Symbios Logic",
    "SymbiosLogic",
    "Symbios",
    "Vitesse",
    "SMC Taiwan",
    "SMCTaiwan",
    "SMC",
    "SLI",
    "Zilog",
    "MATRA TEMIC",
    "MATRATEMIC",
    "MATRA",
    "NSS",
    "POLAR FAB",
    "POLARFAB",
    "POLAR",
    "HEC",
    "LG Electronics",
    "LGElectronics",
    "LG",
    "SVG",
    "Raytheon Semiconductor",
    "RaytheonSemiconductor",
    "Raytheon",
    "GEC P Oldham",
    "GECPOldham",
    "GEC",
    "TPSCo",
    "NEC Europe",
    "NECEurope",
    "KMT Semiconductor",
    "KMTSemiconductor",
    "KMT",
    "Touhoku Univ",
    "TouhokuUniv",
    "Touhoku",
    "AFO Fab 15",
    "AFOFab15",
    "AFO",
    "Tylan General",
    "TylanGeneral",
    "Tylan",
    "Neophotonics (old Lightwave)",
    "Neophotonics(oldLightwave)",
    "Neophotonics",
    "Philips, Albuquerque",
    "Philips,Albuquerque",
    "Philips,",
    "Intersil",
    "Intel - F24",
    "Intel-F24",
    "TSMC - fab14",
    "TSMC-fab14",
    "GF - Fab 7 Singapore",
    "GF-Fab7Singapore",
    "GF",
    "PolarFab - MN",
    "PolarFab-MN",
    "PolarFab",
    "Intel - F12",
    "Intel-F12",
    "X-Fab - Sarawak",
    "X-Fab-Sarawak",
    "X-Fab",
    "Intel - D1D",
    "Intel-D1D",
    "Intel - F32",
    "Intel-F32",
    "SK hynix - M11",
    "SKhynix-M11",
    "Intel - F11x (Service Only)",
    "Intel-F11x(ServiceOnly)",
    "Intel - F17",
    "Intel-F17",
    "GF - Fab 1 Mod 1",
    "GF-Fab1Mod1",
    "GF - Fab 10 Bldg 323",
    "GF-Fab10Bldg323",
    "Intel - Fab 28",
    "Intel-Fab28",
    "TI - DFAB",
    "TI-DFAB",
    "STMicro - AMK6",
    "STMicro-AMK6",
    "STMicro",
    "Sony - Oita",
    "Sony-Oita",
    "Novati Technologies",
    "NovatiTechnologies",
    "Novati",
    "TI - DMOS 6",
    "TI-DMOS6",
    "UMC - HJTC Fab 1",
    "UMC-HJTCFab1",
    "Intel - Fab D1C",
    "Intel-FabD1C",
    "Kioxia - Yokkaichi Fab5",
    "Kioxia-YokkaichiFab5",
    "Kioxia",
    "TSMC - F12C",
    "TSMC-F12C",
    "Fairchild - Penn",
    "Fairchild-Penn",
    "STMicro - Crolles 300",
    "STMicro-Crolles300",
    "Samsung - Line 12",
    "Samsung-Line12",
    "Microchip - OR",
    "Microchip-OR",
    "Intel - IFO, F10/14",
    "Intel-IFO,F10/14",
    "SK hynix - M10",
    "SKhynix-M10",
    "GF - Fab 5 Singapore",
    "GF-Fab5Singapore",
    "Samsung - Line U2 (Cu EF)",
    "Samsung-LineU2(CuEF)",
    "CSBG - Refurb",
    "CSBG-Refurb",
    "CSBG",
    "USJC - B1 (UMC)",
    "USJC-B1(UMC)",
    "USJC",
    "Tower Partners - Arai",
    "TowerPartners-Arai",
    "Anam - Buchon",
    "Anam-Buchon",
    "Samsung - Line U1 (Al EF)",
    "Samsung-LineU1(AlEF)",
    "On Semiconductor",
    "OnSemiconductor",
    "TI - RFAB",
    "TI-RFAB",
    "TI - Miho",
    "TI-Miho",
    "Intel - TD",
    "Intel-TD",
    "UMC - Singapore",
    "UMC-Singapore",
    "Infineon - Technologies Dresden",
    "Infineon-TechnologiesDresden",
    "X-FAB France SAS",
    "X-FABFranceSAS",
    "X-FAB",
    "Samsung - Line 7",
    "Samsung-Line7",
    "STMicro - R8",
    "STMicro-R8",
    "ON Semiconductor Aizu Co., Ltd",
    "ONSemiconductorAizuCo.,Ltd",
    "Denso - Kota",
    "Denso-Kota",
    "Denso",
    "Kioxia - Yokkaichi Fab3",
    "Kioxia-YokkaichiFab3",
    "UMC - 12A",
    "UMC-12A",
    "NXP USA - CHD Fab",
    "NXPUSA-CHDFab",
    "NXP",
    "Infineon Technologies AG - Temecula",
    "InfineonTechnologiesAG-Temecula",
    "Samsung - Line 8",
    "Samsung-Line8",
    "Samsung - Line 9 (LSI II)",
    "Samsung-Line9(LSIII)",
    "SkyWater Technology Foundry, Inc. - F4",
    "SkyWaterTechnologyFoundry,Inc.-F4",
    "SkyWater",
    "Semiconductor Componets Industries",
    "SemiconductorComponetsIndustries",
    "Semiconductor",
    "Winbond - F6",
    "Winbond-F6",
    "NXP USA - ATMC",
    "NXPUSA-ATMC",
    "GF - Fab 9 Burlington",
    "GF-Fab9Burlington",
    "Micron - F6",
    "Micron-F6",
    "TI - DMOS 5N",
    "TI-DMOS5N",
    "JP Semi - Oita",
    "JPSemi-Oita",
    "JP",
    "SMIC - Fab 3B",
    "SMIC-Fab3B",
    "Samsung - S1",
    "Samsung-S1",
    "TI - MFAB",
    "TI-MFAB",
    "Spansion LLC - Fab25",
    "SpansionLLC-Fab25",
    "Intel - RP1",
    "Intel-RP1",
    "STMicro - AMK8E",
    "STMicro-AMK8E",
    "Analog Dev - Cam",
    "AnalogDev-Cam",
    "Microchip - Tempe",
    "Microchip-Tempe",
    "JP Semi - Iwate",
    "JPSemi-Iwate",
    "Samsung - Line 6",
    "Samsung-Line6",
    "SMIC - Fab 4A",
    "SMIC-Fab4A",
    "SMIC - Fab 1",
    "SMIC-Fab1",
    "Intel - China F68 ISST",
    "Intel-ChinaF68ISST",
    "Renesas - Naka",
    "Renesas-Naka",
    "SMIC - Fab 7",
    "SMIC-Fab7",
    "CSMC - Fab 2",
    "CSMC-Fab2",
    "CSMC",
    "DB HiTek Fab 2",
    "DBHiTekFab2",
    "DB",
    "SMIC - Fab 2",
    "SMIC-Fab2",
    "Kioxia - Yokkaichi Fab4",
    "Kioxia-YokkaichiFab4",
    "Samsung - Line M1 (OCS Mod)",
    "Samsung-LineM1(OCSMod)",
    "Vishay Newport Ltd",
    "VishayNewportLtd",
    "Vishay",
    "Kioxia - Yokkaichi Fab2",
    "Kioxia-YokkaichiFab2",
    "Samsung - Line 15",
    "Samsung-Line15",
    "Tower Partners - Uozu",
    "TowerPartners-Uozu",
    "Magna - CJ F5",
    "Magna-CJF5",
    "Magna",
    "STMicro - R2",
    "STMicro-R2",
    "GF - Fab 7G Singapore",
    "GF-Fab7GSingapore",
    "Silterra - Kulim",
    "Silterra-Kulim",
    "SCI LLC DBA On Semiconductor - LSI",
    "SCILLCDBAOnSemiconductor-LSI",
    "SCI",
    "Samsung - Line 13",
    "Samsung-Line13",
    "Sony - Nagasaki",
    "Sony-Nagasaki",
    "Analog Dev - Wilm",
    "AnalogDev-Wilm",
    "NXP USA - OHT - Fab",
    "NXPUSA-OHT-Fab",
    "Intel - F42",
    "Intel-F42",
    "Macronix - F5",
    "Macronix-F5",
    "Intel - F11x - Foveros",
    "Intel-F11x-Foveros",
    "GF - Fab 1 Mod 2",
    "GF-Fab1Mod2",
    "Delco - IN",
    "Delco-IN",
    "Delco",
    "GF - Fab 3 Singapore",
    "GF-Fab3Singapore",
    "GF - Fab 2 Singapore",
    "GF-Fab2Singapore",
    "Micron - F4",
    "Micron-F4",
    "Headway Technologies",
    "HeadwayTechnologies",
    "Headway",
    "Micron - F11",
    "Micron-F11",
    "Sony - Yamagata",
    "Sony-Yamagata",
    "Canon - Ayase",
    "Canon-Ayase",
    "Intel - Fab 28A",
    "Intel-Fab28A",
    "TSMC - Washington",
    "TSMC-Washington",
    "Samsung - Line 16",
    "Samsung-Line16",
    "SK hynix - M12",
    "SKhynix-M12",
    "Concept Systems Mfg",
    "ConceptSystemsMfg",
    "Concept",
    "Skorpios Technologies",
    "SkorpiosTechnologies",
    "Skorpios",
    "Sony - Kumamoto",
    "Sony-Kumamoto",
    "SK hynix - HSCL C2",
    "SKhynix-HSCLC2",
    "TSMC - VIS Singapore",
    "TSMC-VISSingapore",
    "USJC - B2 (UMC)",
    "USJC-B2(UMC)",
    "TSMC - Vanguard",
    "TSMC-Vanguard",
    "Intel - Fab D1X",
    "Intel-FabD1X",
    "TSMC - fab 8A",
    "TSMC-fab8A",
    "HH - Fab 1",
    "HH-Fab1",
    "HH",
    "Fu Dan University",
    "FuDanUniversity",
    "Fu",
    "Renesas - Saijo",
    "Renesas-Saijo",
    "ASMC - Fab 3",
    "ASMC-Fab3",
    "ASMC",
    "TSMC - fab 12",
    "TSMC-fab12",
    "SK hynix - M8",
    "SKhynix-M8",
    "Intel - F15.5",
    "Intel-F15.5",
    "Lapis Semiconductor - Miyagi",
    "LapisSemiconductor-Miyagi",
    "Lapis",
    "ASMC - Fab 2",
    "ASMC-Fab2",
    "SK hynix - M14",
    "SKhynix-M14",
    "Medtronic - Tempe",
    "Medtronic-Tempe",
    "Medtronic",
    "Micron - F10 W",
    "Micron-F10W",
    "Sharp - Fukuyama",
    "Sharp-Fukuyama",
    "Rohm - Hamamatsu",
    "Rohm-Hamamatsu",
    "Rohm",
    "Micron - F16",
    "Micron-F16",
    "SSMC - Singapore",
    "SSMC-Singapore",
    "Inst of Microelec - Sing",
    "InstofMicroelec-Sing",
    "Inst",
    "Teledyne Dalsa Semiconductor",
    "TeledyneDalsaSemiconductor",
    "Teledyne",
    "TSMC - fab 8B",
    "TSMC-fab8B",
    "Micron - F10A",
    "Micron-F10A",
    "TI Japan - Aizu",
    "TIJapan-Aizu",
    "SK hynix - R3",
    "SKhynix-R3",
    "STMicro - CTM8",
    "STMicro-CTM8",
    "Samsung - SRD",
    "Samsung-SRD",
    "TI - Deutschland GmbH",
    "TI-DeutschlandGmbH",
    "Micron MTU - Lehi",
    "MicronMTU-Lehi",
    "Infineon - Malaysia",
    "Infineon-Malaysia",
    "LFoundry - Rousset",
    "LFoundry-Rousset",
    "LFoundry",
    "Intel - China F68 (USE SHAN-ISTF68)",
    "Intel-ChinaF68(USESHAN-ISTF68)",
    "Robert Bosch Semiconductor LLC",
    "RobertBoschSemiconductorLLC",
    "Robert",
    "Natl Inst Adv Industrial AIST",
    "NatlInstAdvIndustrialAIST",
    "Natl",
    "Macronix - F2",
    "Macronix-F2",
    "Tower Partners - Tonami",
    "TowerPartners-Tonami",
    "TI - HFAB",
    "TI-HFAB",
    "Samsung - SAS S2-2 Service",
    "Samsung-SASS2-2Service",
    "Tower - Israel MHFAB",
    "Tower-IsraelMHFAB",
    "TI - LFAB (Lehi)",
    "TI-LFAB(Lehi)",
    "Honeywell - Minn",
    "Honeywell-Minn",
    "Sony - Atsugi",
    "Sony-Atsugi",
    "HH - Fab 3",
    "HH-Fab3",
    "SMIC - Fab 8 (restricted)",
    "SMIC-Fab8(restricted)",
    "Maxim - Beaverton",
    "Maxim-Beaverton",
    "TSMC - F10",
    "TSMC-F10",
    "HH - Fab 2",
    "HH-Fab2",
    "Samsung - P II Project DRAM",
    "Samsung-PIIProjectDRAM",
    "II-VI OptoElectronic",
    "II-VIOptoElectronic",
    "II-VI",
    "GF - Fab 11 Chengdu (See Notes>)",
    "GF-Fab11Chengdu(SeeNotes>)",
    "HP - Fab 21",
    "HP-Fab21",
    "NANYA - F3",
    "NANYA-F3",
    "NANYA",
    "IBM - Yorktown",
    "IBM-Yorktown",
    "TDK - Micronas GmbH",
    "TDK-MicronasGmbH",
    "TDK",
    "Maxim - F10/11",
    "Maxim-F10/11",
    "Samsung - Line 16V",
    "Samsung-Line16V",
    "SMIC - Fab 4B",
    "SMIC-Fab4B",
    "STMicro - Crolles 200",
    "STMicro-Crolles200",
    "Tower Semiconductor San Antonio",
    "TowerSemiconductorSanAntonio",
    "TSMC - fab 6",
    "TSMC-fab6",
    "Qorvo - TX",
    "Qorvo-TX",
    "Qorvo",
    "Yokogawa Mfg.",
    "YokogawaMfg.",
    "Yokogawa",
    "Wuhan Xinxin Semi Mfg Co. Ltd - 3D NAND",
    "WuhanXinxinSemiMfgCo.Ltd-3DNAND",
    "Wuhan",
    "Robert Bosch - GmbH",
    "RobertBosch-GmbH",
    "STMicro - AG8",
    "STMicro-AG8",
    "Micron - F15 Japan",
    "Micron-F15Japan",
    "TSMC - Vanguard Fab2",
    "TSMC-VanguardFab2",
    "PSMC P1 P2",
    "PSMCP1P2",
    "PSMC",
    "Diodes US Manufacturing",
    "DiodesUSManufacturing",
    "Diodes",
    "Sandia Labs - F1",
    "SandiaLabs-F1",
    "Sandia",
    "NXP - ICN8",
    "NXP-ICN8",
    "Institute Of Materials R/E",
    "InstituteOfMaterialsR/E",
    "Institute",
    "EM Microelectronics Marin - Switz",
    "EMMicroelectronicsMarin-Switz",
    "EM",
    "UMC - 8S",
    "UMC-8S",
    "Moses Lake Indus.",
    "MosesLakeIndus.",
    "Moses",
    "Renesas America",
    "RenesasAmerica",
    "GF - Fab 7H Singapore",
    "GF-Fab7HSingapore",
    "Landshut Silicon Foundry GmbH",
    "LandshutSiliconFoundryGmbH",
    "Landshut",
    "Ibiden",
    "Skyworks Solutions",
    "SkyworksSolutions",
    "Skyworks",
    "Canon - Oita",
    "Canon-Oita",
    "Samsung - P III Project DRAM",
    "Samsung-PIIIProjectDRAM",
    "TI - TFab",
    "TI-TFab",
    "AMS OSRAM - AG",
    "AMSOSRAM-AG",
    "UMC - 8C",
    "UMC-8C",
    "Microchip - San Jose/Fortune Drive",
    "Microchip-SanJose/FortuneDrive",
    "Quicksil",
    "Hitachi - DDC",
    "Hitachi-DDC",
    "SK hynix - M15",
    "SKhynix-M15",
    "Micron - F10 N",
    "Micron-F10N",
    "Diodes Semiconductors GB Ltd",
    "DiodesSemiconductorsGBLtd",
    "TSMC - Nanjing fab 16",
    "TSMC-Nanjingfab16",
    "TSMC - fab 15",
    "TSMC-fab15",
    "HH - Fab 5",
    "HH-Fab5",
    "UMC - 8A",
    "UMC-8A",
    "Samsung - Line 16V-B",
    "Samsung-Line16V-B",
    "Spectrolab",
    "TSMC - F15B P5",
    "TSMC-F15BP5",
    "SK hynix - HSCL C2F",
    "SKhynix-HSCLC2F",
    "TSMC - fab 3",
    "TSMC-fab3",
    "Advanced Micro Foundry Pte Ltd",
    "AdvancedMicroFoundryPteLtd",
    "Advanced",
    "Kioxia - Yokkaichi Fab6",
    "Kioxia-YokkaichiFab6",
    "SK hynix - M10C Cu",
    "SKhynix-M10CCu",
    "Kioxia - Kitakami Fab1",
    "Kioxia-KitakamiFab1",
    "Samsung - P III Project NAND",
    "Samsung-PIIIProjectNAND",
    "GF - Fab 8 Malta",
    "GF-Fab8Malta",
    "MIT Lincoln Labs - Lexington",
    "MITLincolnLabs-Lexington",
    "MIT",
    "Samsung - M Project China - II",
    "Samsung-MProjectChina-II",
    "Intel - F22",
    "Intel-F22",
    "IBM - Univ at Albany Nano",
    "IBM-UnivatAlbanyNano",
    "TSMC - F14 P5",
    "TSMC-F14P5",
    "SPIL Suzhou",
    "SPILSuzhou",
    "SemiLED China",
    "SemiLEDChina",
    "SemiLED",
    "Lumentum Operations LLC (Fmr JDSU)",
    "LumentumOperationsLLC(FmrJDSU)",
    "Lumentum",
    "UMC - 8D",
    "UMC-8D",
    "Siliconware Precision Industries",
    "SiliconwarePrecisionIndustries",
    "Siliconware",
    "TSMC - R&D",
    "TSMC-R&D",
    "Infineon - Villach",
    "Infineon-Villach",
    "Hangzhou Fullsemi Technology",
    "HangzhouFullsemiTechnology",
    "Hangzhou",
    "TSMC - F14 P7",
    "TSMC-F14P7",
    "TSMC - F12 P7",
    "TSMC-F12P7",
    "Infineon Technologies AG - El Seg",
    "InfineonTechnologiesAG-ElSeg",
    "SMIC - SMNC B2",
    "SMIC-SMNCB2",
    "SMIC - Fab 16",
    "SMIC-Fab16",
    "SMIC - Fab 4C",
    "SMIC-Fab4C",
    "Samsung - Line M2 (OCS/MC Mod)",
    "Samsung-LineM2(OCS/MCMod)",
    "TSMC - Solid State Lighting",
    "TSMC-SolidStateLighting",
    "SiEn (Qingdao) Integrated Circuits 200mm",
    "SiEn(Qingdao)IntegratedCircuits200mm",
    "SiEn",
    "Mikron - JSC",
    "Mikron-JSC",
    "Mikron",
    "LFoundry S.r.l.",
    "LFoundryS.r.l.",
    "Samsung - Line 11 CIS",
    "Samsung-Line11CIS",
    "TSMC - F18A",
    "TSMC-F18A",
    "UMC - 12B",
    "UMC-12B",
    "IMEC - Leuven",
    "IMEC-Leuven",
    "IMEC",
    "SPIL Cho Plant",
    "SPILChoPlant",
    "Sony - Nagasaki Fab3",
    "Sony-NagasakiFab3",
    "SK hynix - M16",
    "SKhynix-M16",
    "Entegris Asia - Taiwan Branch",
    "EntegrisAsia-TaiwanBranch",
    "Entegris",
    "Avago - Fab B4",
    "Avago-FabB4",
    "Avago",
    "Winbond - F2",
    "Winbond-F2",
    "Amkor - Fab K4",
    "Amkor-FabK4",
    "Amkor",
    "SK hynix - M16 P2",
    "SKhynix-M16P2",
    "Epson - Sakata",
    "Epson-Sakata",
    "Epson",
    "STATS Chip - Fab1",
    "STATSChip-Fab1",
    "STATS",
    "STMicro - AMK6E",
    "STMicro-AMK6E",
    "MEMSCAP",
    "NUVOTON",
    "Samsung - Line 16 II",
    "Samsung-Line16II",
    "Akoustis,  Inc.",
    "Akoustis,Inc.",
    "Akoustis,",
    "TSMC - F12 P4",
    "TSMC-F12P4",
    "Tower Semiconductor Newport Beach",
    "TowerSemiconductorNewportBeach",
    "Phenitec - Okayama",
    "Phenitec-Okayama",
    "Phenitec",
    "STMicro - F1",
    "STMicro-F1",
    "National NanoFab Center",
    "NationalNanoFabCenter",
    "Infineon - Regensburg",
    "Infineon-Regensburg",
    "Kioxia - Yokkaichi Fab7",
    "Kioxia-YokkaichiFab7",
    "StatsChipPac Korea",
    "StatsChipPacKorea",
    "PSMC P3",
    "PSMCP3",
    "TSMC - F12 P6",
    "TSMC-F12P6",
    "SK hynix - M15 P2",
    "SKhynix-M15P2",
    "Samsung - P Project DRAM",
    "Samsung-PProjectDRAM",
    "Chongqing Alpha and Omega Semiconductor",
    "ChongqingAlphaandOmegaSemiconductor",
    "Chongqing",
    "Fairchild - SI MOS 3",
    "Fairchild-SIMOS3",
    "Shanghai Integrated Circuit R&D",
    "ShanghaiIntegratedCircuitR&D",
    "Shanghai",
    "Israel Corp - Tower Semi",
    "IsraelCorp-TowerSemi",
    "Israel",
    "Moxtek - Utah",
    "Moxtek-Utah",
    "Moxtek",
    "TSMC - fab 6B/300mm",
    "TSMC-fab6B/300mm",
    "Samsung - Line 11",
    "Samsung-Line11",
    "Micron - F1A",
    "Micron-F1A",
    "SK hynix - M14 P2",
    "SKhynix-M14P2",
    "Cansemi Technology Inc.",
    "CansemiTechnologyInc.",
    "Cansemi",
    "Micron - Taiwan Backend (MTB)",
    "Micron-TaiwanBackend(MTB)",
    "Canon - Kawasaki",
    "Canon-Kawasaki",
    "GF - Fab 10 Bldg 320 C4",
    "GF-Fab10Bldg320C4",
    "ON Semiconductor - Korea",
    "ONSemiconductor-Korea",
    "Soitec Microelectronics Singapore Pte",
    "SoitecMicroelectronicsSingaporePte",
    "Soitec",
    "Amkor - Hu-Kou T5",
    "Amkor-Hu-KouT5",
    "USJC-Sony JV",
    "USJC-SonyJV",
    "USJC-Sony",
    "ELPIDA - Memory",
    "ELPIDA-Memory",
    "ELPIDA",
    "Vishay Siliconix Itzehoe",
    "VishaySiliconixItzehoe",
    "Nuvoton – Uozu",
    "Nuvoton–Uozu",
    "Nuvoton",
    "Hitachi Global Storage",
    "HitachiGlobalStorage",
    "Intel APF26",
    "IntelAPF26",
    "FLIR Systems",
    "FLIRSystems",
    "FLIR",
    "SMIC - Fab 8 P2 (restricted)",
    "SMIC-Fab8P2(restricted)",
    "On Semiconductor - Czech Republic",
    "OnSemiconductor-CzechRepublic",
    "Winstek Semi (former Statschip)",
    "WinstekSemi(formerStatschip)",
    "Winstek",
    "TSMC - F14 P6",
    "TSMC-F14P6",
    "Robert Bosch - Dresden",
    "RobertBosch-Dresden",
    "HP - F1",
    "HP-F1",
    "Denso - Iwate",
    "Denso-Iwate",
    "TSMC - F15B P6",
    "TSMC-F15BP6",
    "TI - Hiji",
    "TI-Hiji",
    "Avago - Fab B4 Annex",
    "Avago-FabB4Annex",
    "Samsung - S2",
    "Samsung-S2",
    "Samsung - Line 16 DRAM",
    "Samsung-Line16DRAM",
    "TELEFUNKEN - Germany",
    "TELEFUNKEN-Germany",
    "TELEFUNKEN",
    "Samsung - Line U3",
    "Samsung-LineU3",
    "Rohm - Kyoto",
    "Rohm-Kyoto",
    "UMC - 8F",
    "UMC-8F",
    "Qimonda - Dresden (300mm)",
    "Qimonda-Dresden(300mm)",
    "Samsung - M Project China",
    "Samsung-MProjectChina",
    "CSMC - Fab 5",
    "CSMC-Fab5",
    "Samsung - P II Project NAND",
    "Samsung-PIIProjectNAND",
    "X-Fab - Erfurt",
    "X-Fab-Erfurt",
    "Elec-Tech Photoelectric",
    "Elec-TechPhotoelectric",
    "Elec-Tech",
    "HH - Fab 7 Wuxi",
    "HH-Fab7Wuxi",
    "Asahi Kasei Power Devices",
    "AsahiKaseiPowerDevices",
    "Asahi",
    "Lumileds Singapore Pte Ltd",
    "LumiledsSingaporePteLtd",
    "Lumileds",
    "Sony - Kagoshima",
    "Sony-Kagoshima",
    "Samsung - P Project NAND - II",
    "Samsung-PProjectNAND-II",
    "STMicro - R&D",
    "STMicro-R&D",
    "TSMC - Xintec Fab 3",
    "TSMC-XintecFab3",
    "Lumileds LLC",
    "LumiledsLLC",
    "Samsung - Line 14",
    "Samsung-Line14",
    "TSMC - fab 7",
    "TSMC-fab7",
    "Promos - Fab 4",
    "Promos-Fab4",
    "IBM - G450C",
    "IBM-G450C",
    "Blackwatch International DMEA",
    "BlackwatchInternationalDMEA",
    "Blackwatch",
    "Nexperia UK - Hazelgrove",
    "NexperiaUK-Hazelgrove",
    "Nexperia",
    "Toshiba - Isogo",
    "Toshiba-Isogo",
    "Toshiba - Yokohama",
    "Toshiba-Yokohama",
    "Samsung - Line 5",
    "Samsung-Line5",
    "Nissan - Kagaku",
    "Nissan-Kagaku",
    "Nissan",
    "ASE - Fab K7",
    "ASE-FabK7",
    "UMC - 12A P5P6",
    "UMC-12AP5P6",
    "MOS Art - Pack Corp",
    "MOSArt-PackCorp",
    "MOS",
    "Samsung - Line M1B (MC Mod)",
    "Samsung-LineM1B(MCMod)",
    "Dimatix Fujifilm - Fab 1",
    "DimatixFujifilm-Fab1",
    "Dimatix",
    "TSMC - Xintec",
    "TSMC-Xintec",
    "Toshiba - Kaga",
    "Toshiba-Kaga",
    "HP - Fab 30",
    "HP-Fab30",
    "Hitachi Engery - Lenzburg",
    "HitachiEngery-Lenzburg",
    "Samsung - RS Proj",
    "Samsung-RSProj",
    "ASMC - F1",
    "ASMC-F1",
    "IBM - Bldg 323",
    "IBM-Bldg323",
    "STMicro - CTM6",
    "STMicro-CTM6",
    "Renesas - Kofu",
    "Renesas-Kofu",
    "Samsung - Line C1",
    "Samsung-LineC1",
    "Draper Labs - Cambridge",
    "DraperLabs-Cambridge",
    "Draper",
    "X-Fab - Texas",
    "X-Fab-Texas",
    "Microchip - Fab 3",
    "Microchip-Fab3",
    "Samsung - Line 17",
    "Samsung-Line17",
    "NDL - Hsin-Chu",
    "NDL-Hsin-Chu",
    "NDL",
    "Epson - Fujimi",
    "Epson-Fujimi",
    "Samsung - Line 16 III",
    "Samsung-Line16III",
    "Micron - F10N X",
    "Micron-F10NX",
    "Avago - Fab B2",
    "Avago-FabB2",
    "Fujitsu - Atsugi",
    "Fujitsu-Atsugi",
    "DRS - DRS",
    "DRS-DRS",
    "DRS",
    "Casio - Fab 1",
    "Casio-Fab1",
    "Casio",
    "SK hynix - R4",
    "SKhynix-R4",
    "ABLIC Inc.",
    "ABLICInc.",
    "ABLIC",
    "Vishay Siliconix - F3",
    "VishaySiliconix-F3",
    "SOITEC France",
    "SOITECFrance",
    "SOITEC",
    "HP - Fab 22",
    "HP-Fab22",
    "Analog Dev - Lime",
    "AnalogDev-Lime",
    "TSMC - fab 5",
    "TSMC-fab5",
    "Micross Advanced Interconnect Technology",
    "MicrossAdvancedInterconnectTechnology",
    "Micross",
    "Rohm - Apollo",
    "Rohm-Apollo",
    "Lapis Semiconductor - Miyazaki",
    "LapisSemiconductor-Miyazaki",
    "HH - Fab 6",
    "HH-Fab6",
    "Samsung - P Project NAND",
    "Samsung-PProjectNAND",
    "Everspin - Fab 1",
    "Everspin-Fab1",
    "Everspin",
    "SEMC - Fab 1",
    "SEMC-Fab1",
    "SEMC",
    "Yamaha - Kagoshima",
    "Yamaha-Kagoshima",
    "Versum Materials",
    "VersumMaterials",
    "Versum",
    "Maxim - SJ",
    "Maxim-SJ",
    "India Telephone - F1",
    "IndiaTelephone-F1",
    "India",
    "INOTERA - Fab 2",
    "INOTERA-Fab2",
    "INOTERA",
    "Samsung - Line 2(Bump)",
    "Samsung-Line2(Bump)",
    "Jinan BYD Semiconductor",
    "JinanBYDSemiconductor",
    "Jinan",
    "Renesas - Kansai/Shiga",
    "Renesas-Kansai/Shiga",
    "Jireh Semiconductor",
    "JirehSemiconductor",
    "Jireh",
    "Renesas - Kawashiri",
    "Renesas-Kawashiri",
    "TI - SFAB",
    "TI-SFAB",
    "Zhuzhou CRRC Times Electric",
    "ZhuzhouCRRCTimesElectric",
    "Zhuzhou",
    "Renesas - Kochi",
    "Renesas-Kochi",
    "American Air Liquide",
    "AmericanAirLiquide",
    "American",
    "Micron - F13 (>ST-SG8E in Process)",
    "Micron-F13(>ST-SG8EinProcess)",
    "Amkor - T1",
    "Amkor-T1",
    "Boehringer Ingelheim MicroParts Gmbh",
    "BoehringerIngelheimMicroPartsGmbh",
    "Boehringer",
    "UMC - Fab 3",
    "UMC-Fab3",
    "Stanford University",
    "StanfordUniversity",
    "Stanford",
    "MEMC - Singapore",
    "MEMC-Singapore",
    "MEMC",
    "Avantor  - Taiwan",
    "Avantor-Taiwan",
    "Avantor",
    "Mitsubishi - Kumamoto",
    "Mitsubishi-Kumamoto",
    "IBM - Almaden Research Center",
    "IBM-AlmadenResearchCenter",
    "University of Hyogo",
    "UniversityofHyogo",
    "University",
    "JS Foundry Niigata K.K.",
    "JSFoundryNiigataK.K.",
    "JS",
    "TI - Chengdu",
    "TI-Chengdu",
    "SRI International - NJ",
    "SRIInternational-NJ",
    "SRI",
    "PSMC Fab 1",
    "PSMCFab1",
    "Cree, Inc. - Cree",
    "Cree,Inc.-Cree",
    "Cree,",
    "Applied Materials - Santa Clara",
    "AppliedMaterials-SantaClara",
    "Applied",
    "SkyWater Technology Foundry, Inc. - F3",
    "SkyWaterTechnologyFoundry,Inc.-F3",
    "SFA Semicon Co., Ltd.",
    "SFASemiconCo.,Ltd.",
    "SFA",
    "UMC - ATD",
    "UMC-ATD",
    "QUALCOMM - Fab1",
    "QUALCOMM-Fab1",
    "QUALCOMM",
    "Euroimmun Medizinische Labordiagnostika",
    "EuroimmunMedizinischeLabordiagnostika",
    "Euroimmun",
    "Qorvo - F1",
    "Qorvo-F1",
    "USC - Xiamen 12X",
    "USC-Xiamen12X",
    "USC",
    "Qorvo - OR",
    "Qorvo-OR",
    "MMI Semiconductor- Yasu",
    "MMISemiconductor-Yasu",
    "MMI",
    "Skyworks Filter Solutions - Japan",
    "SkyworksFilterSolutions-Japan",
    "NXP - ICFH Hamburg",
    "NXP-ICFHHamburg",
    "TSMC - Chu Nan",
    "TSMC-ChuNan",
    "Mitsubishi - Fukuoka",
    "Mitsubishi-Fukuoka",
    "Rohm - Wako",
    "Rohm-Wako",
    "Aizu Fujitsu - Wakamatsu",
    "AizuFujitsu-Wakamatsu",
    "Aizu",
    "Maxscend Microelectronics Company",
    "MaxscendMicroelectronicsCompany",
    "Maxscend",
    "Samsung - Line 15 PhIII",
    "Samsung-Line15PhIII",
    "University of Texas at Austin",
    "UniversityofTexasatAustin",
    "Nat Univ of Singapore - Sing",
    "NatUnivofSingapore-Sing",
    "Nat",
    "Dicon Fiberoptics",
    "DiconFiberoptics",
    "Dicon",
    "Nexchip Semiconductor",
    "NexchipSemiconductor",
    "Nexchip",
    "Renesas - Takasaki",
    "Renesas-Takasaki",
    "SMIC - Fab 15",
    "SMIC-Fab15",
    "Toshiba - Himeji",
    "Toshiba-Himeji",
    "Wuhan Xinxin Semi Mfg Co. Ltd",
    "WuhanXinxinSemiMfgCo.Ltd",
    "Fraunhofer - IPMS CNT",
    "Fraunhofer-IPMSCNT",
    "Fraunhofer",
    "Rohm - Shiga",
    "Rohm-Shiga",
    "SK hynix - M10E",
    "SKhynix-M10E",
    "Samsung - Line 15 II",
    "Samsung-Line15II",
    "TSMC - FB20 (AP2)",
    "TSMC-FB20(AP2)",
    "STMicro - Tours",
    "STMicro-Tours",
    "Samsung - Line 15 III",
    "Samsung-Line15III",
    "Rong Semiconductor (Huaian)",
    "RongSemiconductor(Huaian)",
    "Rong",
    "Analog Foundries (CUMEC)",
    "AnalogFoundries(CUMEC)",
    "Samsung - Line 13II",
    "Samsung-Line13II",
    "Samsung - P IV Project NAND",
    "Samsung-PIVProjectNAND",
    "Axcelis - Beverly, MA",
    "Axcelis-Beverly,MA",
    "Axcelis",
    "YMTC 3D NAND (restricted)",
    "YMTC3DNAND(restricted)",
    "Dynex Semiconductor",
    "DynexSemiconductor",
    "Dynex",
    "CEA LETI Grenoble",
    "CEALETIGrenoble",
    "CEA",
    "Entrepix - Fab",
    "Entrepix-Fab",
    "Entrepix",
    "Crocus Nano",
    "CrocusNano",
    "Crocus",
    "SPIL ZK Plant",
    "SPILZKPlant",
    "Samsung - ERD",
    "Samsung-ERD",
    "BAE Systems - Lexington, MA",
    "BAESystems-Lexington,MA",
    "BAE",
    "Denso - Hirose",
    "Denso-Hirose",
    "ASE - Fab 12",
    "ASE-Fab12",
    "TSMC - F18 P6 (F18B)",
    "TSMC-F18P6(F18B)",
    "Fuji Electric - Matsumoto",
    "FujiElectric-Matsumoto",
    "ASE - Fab K22",
    "ASE-FabK22",
    "Intermolecular Inc.",
    "IntermolecularInc.",
    "Intermolecular",
    "TSMC - F12 P5",
    "TSMC-F12P5",
    "Epistar N8",
    "EpistarN8",
    "Epistar",
    "Amkor - Fab K5",
    "Amkor-FabK5",
    "JCET Advanced Packaging",
    "JCETAdvancedPackaging",
    "JCET",
    "Shanghai Simgui",
    "ShanghaiSimgui",
    "Semi-Conductor Laboratory - F1",
    "Semi-ConductorLaboratory-F1",
    "Semi-Conductor",
    "BelGaN BV",
    "BelGaNBV",
    "BelGaN",
    "Amkor - Assembly & Test (Shanghai)",
    "Amkor-Assembly&Test(Shanghai)",
    "Epson - Chitose",
    "Epson-Chitose",
    "RF360",
    "X-FAB Dresden",
    "X-FABDresden",
    "Elmos Semiconductor SE",
    "ElmosSemiconductorSE",
    "Elmos",
    "UMC - 8E",
    "UMC-8E",
    "Hitachi - Central Research",
    "Hitachi-CentralResearch",
    "IMS - Stuttgart",
    "IMS-Stuttgart",
    "IMS",
    "BASF Taiwan Ltd.",
    "BASFTaiwanLtd.",
    "BASF",
    "SC Angstrem -T",
    "SCAngstrem-T",
    "SC",
    "Samsung - Line 16V-A",
    "Samsung-Line16V-A",
    "Qorvo US - NC",
    "QorvoUS-NC",
    "SMIC - NRD (restricted)",
    "SMIC-NRD(restricted)",
    "TSMC - F20",
    "TSMC-F20",
    "TSMC - F18 P4",
    "TSMC-F18P4",
    "Novellus - SJ",
    "Novellus-SJ",
    "Novellus",
    "IHP – Institut für Halbleiterphysik",
    "IHP–InstitutfürHalbleiterphysik",
    "IHP",
    "TI - DHC",
    "TI-DHC",
    "Murata Integrated Passive Solutions",
    "MurataIntegratedPassiveSolutions",
    "Murata",
    "Nexperia - GMBH",
    "Nexperia-GMBH",
    "Fraunhofer - Fab 2",
    "Fraunhofer-Fab2",
    "Powertech (PTI)",
    "Powertech(PTI)",
    "Powertech",
    "GTA Semiconductor",
    "GTASemiconductor",
    "GTA",
    "SJ Semi - Jiangyin",
    "SJSemi-Jiangyin",
    "SJ",
    "Hangzhou Lion Micro",
    "HangzhouLionMicro",
    "Wacker Silicone - MI",
    "WackerSilicone-MI",
    "Wacker",
    "Samsung - Line 4",
    "Samsung-Line4",
    "Huatian Technology",
    "HuatianTechnology",
    "Huatian",
    "ASMC Fab 3 - Will Semi",
    "ASMCFab3-WillSemi",
    "Samsung - Line S3V",
    "Samsung-LineS3V",
    "Vivani Medical",
    "VivaniMedical",
    "Vivani",
    "U.C. Berkeley - Cory Hall",
    "U.C.Berkeley-CoryHall",
    "U.C.",
    "On Semi - AZ",
    "OnSemi-AZ",
    "Samsung - Line S3",
    "Samsung-LineS3",
    "INME",
    "STATS Chip - Washington EVAL",
    "STATSChip-WashingtonEVAL",
    "X-Fab MEMS - Erfurt",
    "X-FabMEMS-Erfurt",
    "Samsung - P III Line S6",
    "Samsung-PIIILineS6",
    "Euroimmun AG",
    "EuroimmunAG",
    "Alpha & Omega Semiconductor",
    "Alpha&OmegaSemiconductor",
    "Alpha",
    "Tongfu Microelectronics",
    "TongfuMicroelectronics",
    "Tongfu",
    "Silex Microsystems AB",
    "SilexMicrosystemsAB",
    "Silex",
    "On Semiconductor - SCI LLC",
    "OnSemiconductor-SCILLC",
    "Innotron Memory Co. (restricted)",
    "InnotronMemoryCo.(restricted)",
    "Innotron",
    "SMBC B3",
    "SMBCB3",
    "SMBC",
    "Nisshinbo - Yashiro",
    "Nisshinbo-Yashiro",
    "Nisshinbo",
    "Winbond - Luzhu",
    "Winbond-Luzhu",
    "CXMT Fab2 (restricted)",
    "CXMTFab2(restricted)",
    "CXMT",
    "TSMC - LongTan",
    "TSMC-LongTan",
    "CETHIK Group",
    "CETHIKGroup",
    "CETHIK",
    "Samsung - S1 New Memory",
    "Samsung-S1NewMemory",
    "TF AMD Microelectronics (Penang)",
    "TFAMDMicroelectronics(Penang)",
    "TF",
    "Jiangsu Advanced Memory (AMS)",
    "JiangsuAdvancedMemory(AMS)",
    "Jiangsu",
    "Samsung - Line S5",
    "Samsung-LineS5",
    "Samsung - Line 11 New Memory",
    "Samsung-Line11NewMemory",
    "Fujian Jinhua Integrated Circuit Co.",
    "FujianJinhuaIntegratedCircuitCo.",
    "Fujian",
    "UMC - 8B",
    "UMC-8B",
    "Intel – RA-ATTD",
    "Intel–RA-ATTD",
    "Ningbo Semiconductor",
    "NingboSemiconductor",
    "Ningbo",
    "Renesas - Yamaguchi",
    "Renesas-Yamaguchi",
    "SMEC Shaoxing (200mm)",
    "SMECShaoxing(200mm)",
    "SMEC",
    "CR Micro (Chongqing)",
    "CRMicro(Chongqing)",
    "CR",
    "Industrial Technology Research",
    "IndustrialTechnologyResearch",
    "Industrial",
    "TSMC - Vanguard Fab3",
    "TSMC-VanguardFab3",
    "Fuji Electric - Yamanashi",
    "FujiElectric-Yamanashi",
    "Samsung - Line 1",
    "Samsung-Line1",
    "Shanghai Industrial uTechnology",
    "ShanghaiIndustrialuTechnology",
    "Clas-sic Wafer Fab Ltd",
    "Clas-sicWaferFabLtd",
    "Clas-sic",
    "Yunnan Invensight Optoelectronics",
    "YunnanInvensightOptoelectronics",
    "Yunnan",
    "PSMC Tonglou",
    "PSMCTonglou",
    "USJC / Denso JV",
    "USJC/DensoJV",
    "Xiamen ITRI/USC",
    "XiamenITRI/USC",
    "Xiamen",
    "Diodes Zetex Semi - UK",
    "DiodesZetexSemi-UK",
    "ASE - Fab 11",
    "ASE-Fab11",
    "Hikstor Technology",
    "HikstorTechnology",
    "Hikstor",
    "Tsinghua University",
    "TsinghuaUniversity",
    "Tsinghua",
    "USJC-Sony Nagasaki JV",
    "USJC-SonyNagasakiJV",
    "Yangtze Advanced Memory YAMIIC (restrict",
    "YangtzeAdvancedMemoryYAMIIC(restrict",
    "Yangtze",
    "Research Foundation SUNY Polytechnic",
    "ResearchFoundationSUNYPolytechnic",
    "Research",
    "Showa Denko",
    "ShowaDenko",
    "Showa",
    "TSMC - fab 2",
    "TSMC-fab2",
    "Micron - F15 Japan APD R&D",
    "Micron-F15JapanAPDR&D",
    "BOE Technology Group Co., Ltd.",
    "BOETechnologyGroupCo.,Ltd.",
    "BOE",
    "Taiwan Semiconductor Research Inst NARL",
    "TaiwanSemiconductorResearchInstNARL",
    "Taiwan",
    "Winbond - F1",
    "Winbond-F1",
    "Changxin Jidian Memory CXJD",
    "ChangxinJidianMemoryCXJD",
    "Changxin",
    "Samsung - P II Line S5",
    "Samsung-PIILineS5",
    "Fraunhofer - IFT",
    "Fraunhofer-IFT",
    "Fraunhofer - ISiT",
    "Fraunhofer-ISiT",
    "Facebook Technologies/Plessey",
    "FacebookTechnologies/Plessey",
    "Facebook",
    "SK hynix - M10 CIS",
    "SKhynix-M10CIS",
    "ESPROS Photonics AG",
    "ESPROSPhotonicsAG",
    "ESPROS",
    "Quliang Electronics",
    "QuliangElectronics",
    "Quliang",
    "SiEn (Qingdao) Integrated Circuits 300mm",
    "SiEn(Qingdao)IntegratedCircuits300mm",
    "Canon - Kamisato",
    "Canon-Kamisato",
    "Innostar Semiconductor - Shanghai",
    "InnostarSemiconductor-Shanghai",
    "Innostar",
    "TSMC - F12 P8",
    "TSMC-F12P8",
    "PSMC Powerchip Semiconductor",
    "PSMCPowerchipSemiconductor",
    "Intel - F52",
    "Intel-F52",
    "UC Lawrence Berkeley Lab - Fab 1",
    "UCLawrenceBerkeleyLab-Fab1",
    "UC",
    "STMicro - AG300",
    "STMicro-AG300",
    "Shanghai Integrated Circuit Equipment",
    "ShanghaiIntegratedCircuitEquipment",
    "Aledia",
    "Aledia Champagnier",
    "AlediaChampagnier",
    "CHJS (Chengdu High-tech Jin Science)",
    "CHJS(ChengduHigh-techJinScience)",
    "CHJS",
    "Nantong Tongfu Tech",
    "NantongTongfuTech",
    "Nantong",
    "Changxin Memory Tech CXMT (restricted)",
    "ChangxinMemoryTechCXMT(restricted)",
    "Kokusai Electric",
    "KokusaiElectric",
    "Kokusai",
    "TSMC - Vanguard Fab5",
    "TSMC-VanguardFab5",
    "Honeywell - F1",
    "Honeywell-F1",
    "Ningbo TRS Microelectronics",
    "NingboTRSMicroelectronics",
    "Kioxia - Kitakami Fab2",
    "Kioxia-KitakamiFab2",
    "Zhejiang ICsprout Semiconductor",
    "ZhejiangICsproutSemiconductor",
    "Zhejiang",
    "YMTC 3D NAND Fab 2 (restricted)",
    "YMTC3DNANDFab2(restricted)",
    "Galaxycore Shanghai",
    "GalaxycoreShanghai",
    "Galaxycore",
    "Tower - Italy F10",
    "Tower-ItalyF10",
    "Resources West Microelectronics (RWME)",
    "ResourcesWestMicroelectronics(RWME)",
    "Resources",
    "Kore Semiconductor 200MM",
    "KoreSemiconductor200MM",
    "Kore",
    "Jie Jie Microelectronics (Nan Tong) Tech",
    "JieJieMicroelectronics(NanTong)Tech",
    "Jie",
    "Luxshare - ICT (Van Trung)",
    "Luxshare-ICT(VanTrung)",
    "Luxshare",
    "SMEC Shaoxing (300mm)",
    "SMECShaoxing(300mm)",
    "Shanghai Dingtai Jiangxin Tech.",
    "ShanghaiDingtaiJiangxinTech.",
    "TSMC - F14 P8",
    "TSMC-F14P8",
    "Murata Electronics Oy",
    "MurataElectronicsOy",
    "Wuhan Chuxing Technology",
    "WuhanChuxingTechnology",
    "Fuji Electric (Malaysia)",
    "FujiElectric(Malaysia)",
    "TSMC - Arizona F21",
    "TSMC-ArizonaF21",
    "Semicon Manuf Oriental",
    "SemiconManufOriental",
    "Semicon",
    "TSMC F23 JASM",
    "TSMCF23JASM",
    "Swaysure Technology",
    "SwaysureTechnology",
    "Swaysure",
    "Shanghai GTX Semiconductor",
    "ShanghaiGTXSemiconductor",
    "Canon - Hiratsuka 2nd Plant",
    "Canon-Hiratsuka2ndPlant",
    "PSMC Fab 8B",
    "PSMCFab8B",
    "StarPower Technologies",
    "StarPowerTechnologies",
    "StarPower",
    "PST",
    "UMC Fab12i P3",
    "UMCFab12iP3",
    "Hangzhou HFC Semiconductor",
    "HangzhouHFCSemiconductor",
    "Runpeng Semiconductor (Shenzhen)",
    "RunpengSemiconductor(Shenzhen)",
    "Runpeng",
    "Guangzhou Zen Semiconductor",
    "GuangzhouZenSemiconductor",
    "Guangzhou",
    "StarPower Semiconductor",
    "StarPowerSemiconductor",
    "TSMC - VisEra Technologies Co., Ltd",
    "TSMC-VisEraTechnologiesCo.,Ltd",
    "TSMC - F18 P8",
    "TSMC-F18P8",
    "Huatian Technology(Jiangsu) Co. Ltd.",
    "HuatianTechnology(Jiangsu)Co.Ltd.",
    "Forehope Electronic (Ningbo) 300mm",
    "ForehopeElectronic(Ningbo)300mm",
    "Forehope",
    "HH - Fab 9 Wuxi",
    "HH-Fab9Wuxi",
    "Hefei Xinjing",
    "HefeiXinjing",
    "Hefei",
    "HH - Fab 10",
    "HH-Fab10",
    "UNT-Jiguang",
    "Samsung - Line C3",
    "Samsung-LineC3",
    "Canon/Mitsubishi JV",
    "Canon/MitsubishiJV",
    "Canon/Mitsubishi",
    "Yibu Semiconductor Co., LTD",
    "YibuSemiconductorCo.,LTD",
    "Yibu",
    "ASE - Chung-Li Branch",
    "ASE-Chung-LiBranch",
    "Guangzhou CanSemi IC III",
    "GuangzhouCanSemiICIII",
    "TSMC - F18 P5",
    "TSMC-F18P5",
    "United Test and Assembly Center (UTAC)",
    "UnitedTestandAssemblyCenter(UTAC)",
    "United",
    "Tokyo Electron Ltd.",
    "TokyoElectronLtd.",
    "Tokyo",
    "Beijing Xinli Technology Innovation",
    "BeijingXinliTechnologyInnovation",
    "Beijing",
    "Zing Semiconductor Corporation",
    "ZingSemiconductorCorporation",
    "Zing",
    "Forehope Semiconductor (Ningbo) Co., Ltd",
    "ForehopeSemiconductor(Ningbo)Co.,Ltd",
    "Nantong Tongfu - NTTF",
    "NantongTongfu-NTTF",
    "Rapidus",
    "TSMC - F18 P7",
    "TSMC-F18P7",
    "ATX Semiconductor(Suzhou)",
    "ATXSemiconductor(Suzhou)",
    "ATX",
    "Wuhu Micro Display Intelligent Technolog",
    "WuhuMicroDisplayIntelligentTechnolog",
    "Wuhu",
    "IRAY HEFEI LIMITED",
    "IRAYHEFEILIMITED",
    "IRAY",
    "TSMC - Chu Nan (AP6B)",
    "TSMC-ChuNan(AP6B)",
    "TSMC - F22",
    "TSMC-F22",
    "SK Keyfoundry",
    "SKKeyfoundry",
    "TSMC - AP5B (Taichung)",
    "TSMC-AP5B(Taichung)",
    "Hangzhou Hesheng",
    "Beijing Smartchip",
    "Shanghai Miramems",
    "Fortemedia Holding",
    "Rapidus Corp",
    "Wuyuan Semicon",
    "ED&C",
    "Egypt-Japan Universi",
    "FTD Infocom Pvt Ltd.",
    "FTD Solutions Pte Lt",
    "Georgia Inst of Tech",
    "Goertek Microelectro",
    "Collins Aerospace",
    "George Washington U",
    "Hong Kong U Sci Tech",
    "HORUSEYE TECH ENGENH",
    "Hoseo University",
    "Huazhong U Sci Tech",
    "Hyundai Motor Corp",
    "Indian Institute Tec",
    "IMMS GmbH",
    "Inst Ncl Astrofisica",
    "InvenSense",
    "IPT - Inst Pesquisas",
    "King Abdullah Univ",
    "Khalifa University",
    "KNOWLES ELECTRONICS",
    "Kyoto University",
    "Lab Electro-OpticsSy",
    "MAKSMEMS Design Hous",
    "MEMSIC Semiconductor",
    "Menlo Micro Inc.",
    "Middle East Tech Uni",
    "MIET Ntl Resrch Univ",
    "Zhejiang ICTruth",
    "Guangzhou Zen Semico",
    "LG Display",
    "Dongguan Guangmao",
    "ANHUI JUHE",
    "Mass Precision Sdn",
    "Skyline Semiconductr",
    "Zhuhai Tiancheng Adv",
    "SST Microelectronics",
    "Great Bay Chiple",
    "Xian Longwei Semico",
    "J CUBE SEMICONDUCTOR",
    "Infineon Technologie",
    "Science",
    "LB semicon",
    "Cummins Inc",
    "IIT Kharagpur",
    "Univ Kaiserslautern",
    "West Virginia Univer",
    "King Abdulaziz City",
    "Epirus, Inc.",
    "Shenzhen Pensun Tech",
    "Carnegie Mellon Univ",
    "Rapidus Corporation",
    "Exel",
    "EXSIL",
    "Fangzheng",
    "FLASH Vision",
    "Fraunhofer Institute",
    "Fuji Electric",
    "Fuji Photo",
    "GE",
    "General Dynamics",
    "Gemfire",
    "Gennum",
    "Graybar",
    "GSMC",
    "Gateway University",
    "Henan Polytechnic",
    "Helix Tech",
    "HHNEC",
    "Himeji University",
    "Hitachi Storage",
    "Ichor Systems",
    "IME",
    "IM Flash Singapore,",
    "I-Market Korea",
    "Interface/PBB",
    "INESC",
    "Intermolecular, Inc.",
    "Infotonics",
    "IPDIA",
    "Intl Rectifier",
    "IR Newport",
    "IRST",
    "ISP",
    "ITR Institute",
    "IXYS Semiconductor",
    "JSR",
    "Kaist",
    "Kanematsu",
    "KEC",
    "Kinik",
    "Kionix",
    "Kirim",
    "KLA-Tencor",
    "KST",
    "Linear",
    "Lite-on",
    "L-3",
    "Lawrence Livermore N",
    "Laytron",
    "Maxchip",
    "MagnaChip",
    "Maine Machine",
    "MOS Art Pack Corpora",
    "Marsica (MIT)",
    "MEI",
    "MHS",
    "Microsemi",
    "Miyazaki",
    "Mosel",
    "Max Planck Institute",
    "MRDC",
    "Mississippi State Un",
    "Murata Electronics",
    "MXIC",
    "North Coast Electric",
    "North East Silicon",
    "NIAIST",
    "Ningo",
    "Nippon",
    "Nissan Chemical",
    "Northern Lights semi",
    "Nanker",
    "Nova Measuring",
    "Northrop",
    "Nortel",
    "New Japan Radio",
    "NTU",
    "Numonyx",
    "NUS",
    "State University of",
    "Omron",
    "Olivetti Tech Center",
    "Owens Design",
    "Parolink",
    "PCC",
    "Perkin Elmer",
    "Peregrine",
    "Philips Lumileds",
    "Plessey Semi",
    "PPG",
    "ProMOS",
    "PSI Repair",
    "Pure Wafer",
    "Qualcomm",
    "RFMD (UK) LTD.",
    "Rohm and Haas",
    "Ricoh",
    "Rockwood",
    "Research Triangle",
    "Sanmina",
    "Saudi Electronic",
    "Sarnoff",
    "Sawtek",
    "Sandia Lab",
    "SCL",
    "Sandisk",
    "Seiko Instruments",
    "Semi Scenic",
    "Shinko",
    "Shanghai IC",
    "SinoMOS",
    "Sipex",
    "SITAR",
    "SIS",
    "SIT",
    "Six Semiconductores",
    "Sumpro",
    "Semisouth",
    "Sumitomo",
    "SOE",
    "Leading Edge SemiTec",
    "TF AMD Micr",
    "Southwest Sillicon",
    "SRISA",
    "SRI International",
    "S3",
    "SSC SynTec",
    "Silicon Sensor Intl",
    "Stats ChipPac",
    "STC",
    "SFA Semicon",
    "Sumco",
    "Suntron",
    "Supertex",
    "Seoul University",
    "SVTC Technologies",
    "Symmorphix",
    "Tachyonics",
    "Taisil",
    "Taiwan Semicon",
    "Tateyama",
    "Techlink",
    "TEL",
    "Tech Serv",
    "Thermatek",
    "Telefunken",
    "Tokai Carbon",
    "Toppan Printing",
    "TriQuint",
    "Tronics",
    "Tracit Tech",
    "Truesense Imaging",
    "TSC",
    "University at Albany",
    "UC Berkeley",
    "United Monolithic Se",
    "United Vision",
    "U of Michigan",
    "Unitive Semi",
    "VAT",
    "Victor",
    "VIS",
    "Vitelic",
    "VTT",
    "Western Digital",
    "West European Silico",
    "Wafertech",
    "WLCSP",
    "WMI",
    "Zhejiang ChipRight",
    "WuXin Semiconductor",
    "Zhe Jiang Super Dim",
    "Shanghai Ciyu Tech",
    "Dongguan Rayxin",
    "VTE KOREA Co.,Ltd",
    "MIREA Russian Tech U",
    "MKU Limited",
    "Nanjing Uni of Posts",
    "Nat Ctr High-Perform",
    "Ntl Uni Sci & Techno",
    "National Taiwan Univ",
    "NXTSENS Microsystems",
    "Pioneer Smart Sensin",
    "QST Solutions Limite",
    "Ryerson University",
    "Space Application Ce",
    "San Diego State Univ",
    "SAFRAN",
    "Simon Fraser Univers",
    "Sheba Microsystems",
    "ShanghaiTech Univers",
    "SITRI-Shanghai Indus",
    "SiEn (Qingdao) Integ",
    "SK hynix Inc - Logic",
    "Shaoxing Institute",
    "Solid State Physics",
    "Southern Uni Sci Tec",
    "St. Petersburg Poly",
    "STFC-Sci Tech Facili",
    "Stevens Inst Techno",
    "Thiagarajar College",
    "TSE Co., Ltd.",
    "Tech Univ Muenchen",
    "Univ of Alabama",
    "UniAuto Ciudad Juare",
    "Uni of Extremadura",
    "Uni of Louisville",
    "UNAM U Nacional Auto",
    "Uni of New Castle",
    "U of New Mexico",
    "Uni of Pittsuburgh",
    "Uni of South Florida",
    "U Western Australia",
    "Univ of Waterloo",
    "WiSpry, Inc.",
    "Wuhan University",
    "Xilinx, Inc.",
    "Yitoa Microtechnolog",
    "Resources West Micro",
    "Heifei Payton storag",
    "Wuhu Micro-Displayer",
    "Fabmatics GmbH",
    "Silicon Austria Labs",
    "Heifei Xinjing Semi",
    "ESIEE Paris",
    "StarPower Technolog",
    "Jiangsu Nepes Semi",
    "Arizona State Univer",
    "Rong Semiconductor",
    "Yibu Semiconductor",
    "Jiangsu Silicon Inte",
    "Keio University",
    "Kokusai Electric Co",
    "Hon Young Semiconduc",
    "Unisem",
    "Sidtek Anhui Semicon",
    "MMI Semi",
    "PXW Semiconductor",
    "Forehope Electronic",
    "TRS Microelectronics",
    "Nitte Meenakshi Inst",
    "Onto Innovation",
    "University Minnesota",
    "Aceinna, Inc.",
    "Dortmund Semiconduct",
    "FORMEDIA SARL",
    "Guangzhou Bay Area",
    "Principal Serv Solu",
    "Wuhan Chuxing Techno",
    "JHICC",
    "Sky Chip Interconnec",
    "Japan Material Co.",
    "Guangdong 3D-Semi Co",
    "Shiv Nadar Universit",
    "Indian Inst Science",
    "NIL Technology",
    "SwaySure Technology",
    "Futaba Electric Tele",
    "Aalto University",
    "Atomica",
    "Hubei XinweiguangMic",
    "PixelEXX Systems",
    "Suzhou Global Sensor",
    "Kuwait Colleg SciTec",
    "CR Runan Technologie",
    "Beijing HFI Electron",
    "UC Irvine",
    "Jinan BYD Semiconduc",
    "Zhejiang Hexin Integ",
    "IRay Technology",
    "EMD Versum Materials",
    "Hana Micron",
    "Tianfu Xinglong Lake",
    "Zing Semiconductor",
    "Ji Guang Semiconduct",
    "Zuhai Hengqin Jointe",
    "Alpha Tech Limited",
    "FEL Corp",
    "Luxis Precision Inte",
    "EMAG Technologies",
    "Graser Technology",
    "Korea University",
    "Myongji University",
    "Sensata Technologies",
    "Suwa University",
    "TRUMPF GmBH",
    "Tech Univ Darmstadt",
    "University of Cyprus",
    "Univ of Edinburgh",
    "University of Ulsan",
    "14ACMOS",
    "Analog Foundries",
    "Broadex Technologies",
    "Classic Wafer Fab",
    "BOE Technology Grp",
    "Shenzhen Qili Tech",
    "2JK Semi",
    "3D Glass",
    "Aishin Seiki",
    "Avalanch Tech",
    "AVX Corp",
    "Advanced Wireless",
    "Bookham Tech",
    "Case Western",
    "Charm and Ci",
    "Changchun Changguang",
    "Communications Sys",
    "Du Pont",
    "Emagin",
    "Fondazione Bruno Kes",
    "Fudan Univ Shanghai",
    "Femto ST UFC",
    "Flipchip",
    "Global Comm Tech",
    "Goodrich Sensor Sys",
    "Higashine Shindengen",
    "Intl Microelec Prod",
    "IQE Silicon Compound",
    "JCG Catalysts Chems",
    "Joint School Nanosci",
    "JVC Kenwood",
    "Kashiyama USA",
    "Kwang Electronics",
    "Low Power Electronic",
    "MA Com Inc",
    "Micralyne",
    "Mitsumi Electric",
    "Mapper LLC",
    "Memsic Semi",
    "North Carolina State",
    "Nitta Haas",
    "NTT",
    "Omni Vision Tech",
    "Ramtron Intl",
    "Suntek Compound",
    "Seagate",
    "Silicon Microstruct",
    "Sumitomo Sitix",
    "Standard MEMS",
    "SVG Lithography",
    "Unipac Opto",
    "Wacker Siltronic",
    "Xerox",
    "Yamagata Sanken",
    "II-VI Compound Semi",
    "Ntl Applied Rsrch",
    "Shinryo",
    "Wuhan HSMC",
    "United Semi",
    "Xiamen ITRI",
    "Zhejiang Hikstor",
    "Inst Mat Res & Eng",
    "Yangtze Advanced Mem",
    "Showa Denko K.K.",
    "Quanxin IC Mfg-QXIC",
    "Lynred by Sofradir",
    "PREMA Semi",
    "Metryx",
    "VIAVI Solutions",
    "SSEMVIT",
    "HeFeChip",
    "Ferrotec (AnHui)",
    "JM Engineering",
    "Projekt Service Pete",
    "Innostar Semi",
    "Siwave",
    "NCAP",
    "Ideal Semi",
    "IQM Finland Oy",
    "Shanghai Xianfang",
    "Innoscience",
    "CR Micro",
    "Semikron Elektronik",
    "Suzuki Shokan",
    "Illumina",
    "Shanghai Int Circuit",
    "Chengdu Hi-tech Jin",
    "Daimler-Chrysler Aer",
    "Changxin Jidian Mem",
    "TOTO LTD.",
    "Maxscend Microelectr",
    "Dingtai Jiangxin Tec",
    "Intersec",
    "Zhejiang ICsprout Se",
    "Hangzhou Fullsemi Te",
    "Plexus Electronica",
    "Jie Jie Microelectro",
    "JCET Semiconductor",
    "Zhejiang Hichip Micr",
    "Luxshare Electronic",
    "Shangdong Qixin Mems",
    "Blackwatch Intl Corp",
    "Hangzhou HFC Semicon",
    "CEZAMAT Warsaw Univ",
    "HannStar Display Cor",
    "Kore Semiconductor",
    "Xiamen sky Semicond",
    "HRL Laboratories",
    "Innoseis Sensor Tech",
    "STC “Design Center”,",
    "Uni SciTec ChinaUSTC",
    "AEPONYX, Inc.",
    "AEYE Inc",
    "AONE SOFT TECHS",
    "Asml Netherlands Bv",
    "Aselsan",
    "Carl Zeiss SMT GmbH",
    "CJSC ClosedJointStoc",
    "CMC Microsystems",
    "ChangXin Memory Tech",
    "CNFM",
    "TATA Semiconductor",
    "Huahong Integrated",
    "Ebara Refrigeration",
    "Hansol",
    "YOFC Advanced Semi",
    "VM Inc.",
    "G&W ELECTRIC COMPANY",
    "Chonnam University",
    "Nepes corporation",
    "MemLog GmbH",
    "Beijing Electronics",
    "Graphenea",
    "JS Foundry Nigata",
    "ATX Semiconductor",
    "Beijing ICLink Tech",
    "Canadian Microelectr",
    "Samsung Electro-Mech",
    "Sunny Omnlight Tech",
    "EMP Shield",
    "JiangSu Nexic",
    "Beijing Xinli Tech",
    "Hunan Sanan Semicon",
    "LUXSHARE PRECISION L",
    "VisEra Technologies",
    "United Test & Asmbly",
    "Jiechuwei",
    "Iota Biosciences",
    "Powertech Technology",
    "Japan Advanced Semic",
    "Runpeng Semicon",
    "Hubei Yangtze Labs",
    "Longshine (Xiamen)",
    "SICPA Italia S.p.A.",
    "Xinlian Micro",
    "Anhui Xinshijia Semi",
    "Huizhou Biwin Stg",
    "Maxscend Semiconduct",
    "AEROSPAZIO Tecnologi",
    "Suzhou TF-AMD",
    "Shenzhen Xiu Yuan",
    "WaveOptics",
    "Yongxin Technology",
    "Shanghai Optoelectro",
    "Axcelis Technologies",
    "Yongjiang Lab",
    "Shanghai GTX Semicon",
    "Guangdong Ziyue Semi",
    "PEWl Receivin",
    "Univ of Tech Sydney",
    "Shenzhen Pengxinxu",
    "C&D Co",
    "SEC Chip Industry",
    "ASP Tech",
    "Agni Semiconductor L",
    "SiTime",
    "European Sensors Sys",
    "I-STEM IISC",
    "Adv Goldenchip",
    "CENTRE DE COLLAB",
    "Shanghai PuSmart",
    "Okuno Chemical Indus",
    "Onondaga College",
    "Edwards Limited",
    "Shanghai Ind Tech",
    "Xidian University",
    "Xintec",
    "Zetex",
    "ZMD",
    "Apple",
    "Huaian Imag Dev Mfg",
    "Huawei Tech Co",
    "Rokko",
    "Veeco",
    "Shanghai Ind MTech",
    "Nexchip Semi",
    "Zhiju Semi (Hefei)",
    "Nano Precision Med",
    "Maruyama Mfg Corp",
    "Okmetic Oyj",
    "Preston Business Utd",
    "Skywater",
    "SK Hynix Systems IC",
    "Jiangsu Adv Memory",
    "Newport Wafer Fab",
    "Akoustis",
    "Tacoma Nanjing Semi",
    "Accelink Denmark",
    "Ningbo Semi",
    "Intl Microcircuits",
    "Skorpios Tech",
    "Ibsen Photonics",
    "Kunming BOE Display",
    "SKC Solmics",
    "AMS Sensors Asia",
    "Cansemi Technology",
    "Shanghai Adv Res Ins",
    "Beijing Yandong Micr",
    "Advanced Micro Fndry",
    "Shenhe Thermo-Magnet",
    "Japan Semiconductor",
    "Nakajima Industrial",
    "Shanghai Jiuhe I&E",
    "SiEn Qingdao IC",
    "PragmaticIC",
    "Step Science",
    "Talus",
    "CEA Leti",
    "AAC Tech",
    "AK Power Devices",
    "Anadigics",
    "Alpha & Omega Semi",
    "Arrows Engineering",
    "CISC",
    "College of NSE",
    "Compound Photonics",
    "ConceptPart Solution",
    "E Dot Technology",
    "Espros Photonics",
    "EU Plasma Tech",
    "Edge Semicon",
    "E Top Advance",
    "Fujifilm",
    "Global Comm Semi",
    "GeneralSemiconductor",
    "Global Wafers JP Co",
    "Hagemeyer",
    "HH Grace",
    "Human Inc",
    "Ind Distro Group",
    "JDSU",
    "Kotec",
    "Lapis Semiconductor",
    "Lam Forecast",
    "Lam Research",
    "Masse",
    "Magic Technologies",
    "Moses Lake Industrie",
    "Motion Industries",
    "Memsstar",
    "Nichia",
    "NMRC",
    "Nanium",
    "Piotech",
    "Pentagon Tech",
    "Scientific and Mfg",
    "Strategic E Alliance",
    "Semefab",
    "Sensirion",
    "Setech",
    "Skysilicon",
    "SilannaSemiconductor",
    "SSTC",
    "Simple Tech",
    "Semi-Tech Intl",
    "Siltronic",
    "SUNY Research",
    "TD Semiconductor",
    "Toyota Motor Co",
    "Trillium",
    "TSI Semiconductor",
    "Teltec",
    "TowerJazz",
    "University of Texas",
    "UTi Inv Mgmt",
    "Wafer Works",
    "XMC",
    "ZAO Syntez Micro",
    "AG Semiconductor",
    "Delft Univ of Tech",
    "Kuritec",
    "Jiangyin Changdian A",
    "Unitec Semi S.A.",
    "Hamamatsu Photonics",
    "Huatian Tech Electro",
    "Nantong Fujitsu Micr",
    "SJ Semiconductor",
    "Enthone",
    "Cerma Precision",
    "MCNC",
    "RF Micro - NC",
    "Osram Opto Semi",
    "Greatek",
    "Hangzhou Silan",
    "Shanghai Will Semi",
    "Shenzhen HiSilicon",
    "3M",
    "ABB",
    "AE",
    "Agilent",
    "Ares Green Tech",
    "Air Products",
    "Alcatel",
    "Alien Tech",
    "Allegro",
    "Air Liquide",
    "Applied micro circui",
    "AMPI",
    "Amtec",
    "Angstrem",
    "Applied Industrial",
    "APMI",
    "Applied Materials",
    "Army Research Lab",
    "Aspect",
    "ATDF",
    "ATMI",
    "Atmel",
    "AU Optronics",
    "Axus",
    "B2B",
    "Belling",
    "Boehringer Ingelheim",
    "BOC Edwards",
    "Key Foundry",
    "Kanto Chemical Co.",
    "Robert Bosch",
    "Bridgelux",
    "Brooks",
    "Bruckner",
    "Cabot",
    "Calogic Corp",
    "California Micro",
    "Cension",
    "Chartered",
    "China Electronics",
    "CINOS",
    "CNU",
    "Concept Systems",
    "CoorsTek",
    "Corus",
    "Covalent",
    "Cree",
    "CSR Zhuzhou",
    "CSWC",
    "Crosstown Mechanical",
    "Dallas Semiconductor",
    "Dublin City Universi",
    "Diodes Fabtech",
    "Dongbu HiTek Co",
    "DPIX",
    "Draper Labs",
    "Data Strorage Inst",
    "Dynex Semi",
    "E2V",
    "Eastman Kodak",
    "EDD",
    "Ele Eng computer",
    "EKC",
    "EMA",
    "EM Marin",
    "EPCOS",
    "Episil",
    "EverspinTechnologies",
    "Elec-Tech Photoelect",
    "Luxshare - ICT Comp",
    "HHM",
    "BSS",
    "SMM",
    "FHC",
    "RPD",
    "WST",
    "EDC",
    "EGY",
    "FT1",
    "FT2",
    "GIT",
    "GOE",
    "COL",
    "GWU",
    "HKU",
    "HOR",
    "HOS",
    "HUS",
    "HYU",
    "IIT",
    "IMM",
    "INA",
    "INV",
    "IPT",
    "KAU",
    "KHA",
    "KNO",
    "KYO",
    "LEO",
    "MAK",
    "ME1",
    "MEN",
    "MID",
    "MIE",
    "ZIC",
    "GZS",
    "LGD",
    "DGT",
    "AJM",
    "MPS",
    "SSL",
    "ZTA",
    "SSM",
    "GBC",
    "XLS",
    "JCS",
    "SNC",
    "LBN",
    "CMS",
    "IIK",
    "UKS",
    "WVU",
    "KAC",
    "EPR",
    "SHP",
    "CMU",
    "RAP",
    "EXE",
    "EXS",
    "FAI",
    "FLA",
    "FLI",
    "FRA",
    "FRE",
    "FUE",
    "FUJ",
    "FUP",
    "GE1",
    "GED",
    "GEM",
    "GEN",
    "GF1",
    "GRA",
    "GSM",
    "GTU",
    "HEN",
    "HET",
    "HHN",
    "HIU",
    "HON",
    "HP1",
    "HTS",
    "HUA",
    "HYN",
    "IBI",
    "ICH",
    "IMC",
    "IMF",
    "IMK",
    "INB",
    "INE",
    "INF",
    "INL",
    "INM",
    "INO",
    "INS",
    "INT",
    "IPD",
    "IRC",
    "IRN",
    "IRS",
    "ITR",
    "IXY",
    "JAZ",
    "JIR",
    "KAI",
    "KAN",
    "KIN",
    "KIO",
    "KIR",
    "KLA",
    "LFR",
    "LIN",
    "LIT",
    "LL3",
    "LLL",
    "LTR",
    "LUC",
    "MAC",
    "MAG",
    "MAM",
    "MAR",
    "MED",
    "MEM",
    "MEP",
    "MIC",
    "MII",
    "MIK",
    "MIL",
    "MIP",
    "MIS",
    "MIY",
    "MOX",
    "MPI",
    "MRD",
    "MSU",
    "MTS",
    "MUR",
    "MXI",
    "NAN",
    "NAT",
    "NCE",
    "NEP",
    "NES",
    "NIA",
    "NIN",
    "NIP",
    "NIS",
    "NLS",
    "NNK",
    "NOA",
    "NOP",
    "NOR",
    "NOV",
    "NPR",
    "NTS",
    "NUM",
    "NVM",
    "NVT",
    "NYU",
    "OKI",
    "OMR",
    "ONS",
    "OTC",
    "OWD",
    "PAN",
    "PAR",
    "PEE",
    "PHE",
    "PHI",
    "PHL",
    "PLS",
    "POL",
    "PRO",
    "PSC",
    "PSI",
    "PWI",
    "PWT",
    "QIM",
    "QUA",
    "REN",
    "REX",
    "RFM",
    "RHE",
    "RIC",
    "ROC",
    "ROH",
    "RTI",
    "SAA",
    "SAE",
    "SAF",
    "SAK",
    "SAM",
    "SAN",
    "SAO",
    "SDK",
    "SEI",
    "SEL",
    "SES",
    "SHA",
    "SHE",
    "SHI",
    "SIC",
    "SIL",
    "SIN",
    "SIP",
    "SIR",
    "SIX",
    "SKY",
    "SMI",
    "SMS",
    "SMT",
    "SOI",
    "SON",
    "LST",
    "TAM",
    "SOS",
    "SPA",
    "SPI",
    "SRA",
    "SS3",
    "SSC",
    "SSI",
    "ST1",
    "STA",
    "STS",
    "STU",
    "SUM",
    "SUN",
    "SUP",
    "SUS",
    "SVT",
    "SYM",
    "TAC",
    "TAI",
    "TAS",
    "TAT",
    "TEC",
    "TES",
    "TI1",
    "TLF",
    "TOC",
    "TOS",
    "TOW",
    "TRI",
    "TRO",
    "TRT",
    "TRU",
    "TSM",
    "UAA",
    "UCB",
    "UMS",
    "UNV",
    "UOM",
    "UST",
    "VAN",
    "VIC",
    "VIE",
    "VIT",
    "VIY",
    "WDT",
    "WES",
    "WFT",
    "WIN",
    "WLC",
    "XFB",
    "ZCR",
    "WXS",
    "ZJS",
    "SCT",
    "DRI",
    "VTE",
    "MIR",
    "MKU",
    "NAU",
    "NCH",
    "NST",
    "NTA",
    "NXT",
    "PIN",
    "QST",
    "RYE",
    "SAC",
    "SDU",
    "SFN",
    "SFU",
    "SHM",
    "SHU",
    "SI1",
    "SIE",
    "SM1",
    "SOL",
    "SOU",
    "SPB",
    "STF",
    "STT",
    "THI",
    "TSE",
    "TUM",
    "UAL",
    "UCJ",
    "UEX",
    "ULO",
    "UNA",
    "UNC",
    "UNM",
    "UOP",
    "USF",
    "UWA",
    "UWL",
    "WSP",
    "WUH",
    "XIL",
    "YIT",
    "RWM",
    "HPS",
    "WMD",
    "FAB",
    "SAL",
    "HXS",
    "GRO",
    "SPT",
    "JNS",
    "ASU",
    "RON",
    "YIW",
    "JSI",
    "KEO",
    "KE1",
    "HY1",
    "UNS",
    "SID",
    "PXW",
    "FHE",
    "TRS",
    "NTE",
    "ONT",
    "UMI",
    "ACE",
    "DS1",
    "FRM",
    "GBA",
    "PSS",
    "WCT",
    "JHI",
    "JM1",
    "G3S",
    "SNU",
    "IIS",
    "NIL",
    "SWY",
    "FUT",
    "AAL",
    "ATO",
    "HUB",
    "PIX",
    "SGS",
    "KCS",
    "CRR",
    "HFI",
    "ACI",
    "UCI",
    "JBY",
    "ZHI",
    "IRA",
    "EMD",
    "HNM",
    "TXL",
    "ZIN",
    "JGS",
    "ZHJ",
    "APT",
    "FEL",
    "LXP",
    "EM1",
    "GRS",
    "KOU",
    "MYU",
    "SNS",
    "SUW",
    "TRP",
    "TUD",
    "UCY",
    "UED",
    "UOU",
    "14A",
    "ANF",
    "BRD",
    "CLA",
    "SQT",
    "2JK",
    "3DG",
    "AIS",
    "AVL",
    "AVX",
    "AWS",
    "BOO",
    "CAW",
    "CCS",
    "CCY",
    "CSE",
    "DPT",
    "EMG",
    "FBK",
    "FDU",
    "FEM",
    "FLP",
    "GCT",
    "GOO",
    "HIG",
    "IMP",
    "IQE",
    "JGC",
    "JSN",
    "JVC",
    "KAS",
    "KWA",
    "MAI",
    "MCR",
    "MPP",
    "MSC",
    "NCS",
    "NIT",
    "OVT",
    "QUI",
    "RAM",
    "SCS",
    "SGT",
    "SPE",
    "SSS",
    "STN",
    "UNP",
    "WAC",
    "XER",
    "YSK",
    "IIV",
    "NAR",
    "SHN",
    "WHS",
    "XIA",
    "ZHT",
    "ALE",
    "IMR",
    "TSB",
    "YAD",
    "SHO",
    "SP1",
    "QXI",
    "FAC",
    "LBS",
    "PRE",
    "MET",
    "EUI",
    "VIA",
    "SSE",
    "GAL",
    "HFC",
    "FER",
    "JME",
    "PSP",
    "IST",
    "SIW",
    "NCA",
    "IDE",
    "IQM",
    "SXS",
    "INC",
    "CRM",
    "SMK",
    "QUE",
    "SUZ",
    "ILL",
    "SHC",
    "CHJ",
    "DCA",
    "BEJ",
    "TOT",
    "MXS",
    "DTJ",
    "ITC",
    "ZIS",
    "HFS",
    "PLE",
    "JIE",
    "JCE",
    "ZHM",
    "LUX",
    "SQM",
    "BIC",
    "TR1",
    "CEZ",
    "HN1",
    "KOR",
    "XSS",
    "HRL",
    "1IS",
    "1ST",
    "1UC",
    "AEP",
    "AEY",
    "AON",
    "ASL",
    "ASN",
    "CAR",
    "CJS",
    "CMC",
    "CMT",
    "CNF",
    "TAA",
    "HIC",
    "EBA",
    "HSO",
    "YAS",
    "VM1",
    "G&W",
    "CH1",
    "NPC",
    "MLG",
    "BEH",
    "GPH",
    "JSF",
    "BIT",
    "SMA",
    "SOT",
    "EMP",
    "JNT",
    "BXT",
    "HSS",
    "LPL",
    "VRA",
    "UTC",
    "WCH",
    "HJS",
    "IOT",
    "PTI",
    "JAS",
    "HYL",
    "LXT",
    "SPS",
    "XLM",
    "AXS",
    "HBS",
    "MAE",
    "AES",
    "STD",
    "SXY",
    "WAV",
    "YON",
    "SOP",
    "AXT",
    "YJL",
    "GTX",
    "GND",
    "APR",
    "UTS",
    "CDC",
    "SEC",
    "AST",
    "AGM",
    "SII",
    "EUS",
    "ISE",
    "AGC",
    "CDE",
    "SPU",
    "OCI",
    "ONO",
    "ELD",
    "SIU",
    "XID",
    "XIN",
    "YAM",
    "YOK",
    "ZET",
    "ZIL",
    "APL",
    "HID",
    "HTC",
    "LUM",
    "SLX",
    "ROK",
    "TON",
    "VEE",
    "NEX",
    "SIM",
    "ZSC",
    "NPM",
    "YMT",
    "MMC",
    "OKM",
    "PBU",
    "SKW",
    "HYS",
    "JAM",
    "INN",
    "NWF",
    "AKO",
    "TNS",
    "ACC",
    "NSI",
    "IMI",
    "SKO",
    "IBS",
    "KBD",
    "SKC",
    "AMA",
    "CTI",
    "SAR",
    "BYM",
    "AMF",
    "SME",
    "STM",
    "JSC",
    "NAK",
    "SJI",
    "SQI",
    "PPL",
    "STP",
    "TAL",
    "AAC",
    "AKP",
    "ANA",
    "AOS",
    "ARR",
    "CIS",
    "CNS",
    "COM",
    "CPS",
    "EDT",
    "ELM",
    "EPH",
    "EPT",
    "ESE",
    "EST",
    "ETA",
    "FUF",
    "GCS",
    "GSC",
    "GWJ",
    "HAG",
    "HHG",
    "HUM",
    "IDG",
    "IMN",
    "JDS",
    "KOT",
    "LAP",
    "LMF",
    "LMR",
    "MAS",
    "MGT",
    "MLI",
    "MOI",
    "MSS",
    "NIC",
    "NMR",
    "NNM",
    "PIO",
    "PTT",
    "RAY",
    "SCM",
    "SEA",
    "SEM",
    "SEN",
    "SKS",
    "SSA",
    "SST",
    "STE",
    "STI",
    "STR",
    "SUR",
    "TDS",
    "THU",
    "TMC",
    "TRL",
    "TSI",
    "TTE",
    "TWJ",
    "UOT",
    "UTI",
    "WWO",
    "ZAO",
    "AGS",
    "BAS",
    "DFT",
    "HEA",
    "KUR",
    "JCA",
    "UNI",
    "HAM",
    "HTE",
    "NFM",
    "SJS",
    "ENH",
    "CER",
    "MCN",
    "RFN",
    "WIS",
    "CET",
    "HLM",
    "OOS",
    "GRE",
    "HAN",
    "SWS",
    "SHT",
    "3M1",
    "ADT",
    "AE1",
    "AGE",
    "AGI",
    "AGT",
    "ALC",
    "ALI",
    "ALQ",
    "ALT",
    "AMC",
    "AMK",
    "AMT",
    "ANG",
    "API",
    "APM",
    "APP",
    "ARL",
    "ASM",
    "ASP",
    "ATD",
    "ATL",
    "ATM",
    "AUO",
    "AVA",
    "AXC",
    "AXU",
    "BEL",
    "BIM",
    "BOC",
    "KEY",
    "KCC",
    "BOS",
    "BRI",
    "BRO",
    "BRU",
    "CAB",
    "CAL",
    "CAM",
    "CAS",
    "CEN",
    "CHA",
    "CHE",
    "CIN",
    "CON",
    "COO",
    "COR",
    "COV",
    "CRE",
    "CRO",
    "CSR",
    "CSW",
    "CTM",
    "CYP",
    "DAL",
    "DCU",
    "DEL",
    "DEN",
    "DIC",
    "DIO",
    "DON",
    "DPI",
    "DRA",
    "DSI",
    "DYS",
    "EAK",
    "EEC",
    "ELP",
    "EMM",
    "ENT",
    "EPC",
    "EPI",
    "EPS",
    "ETI",
    "ETP",
    "LIC",
]


customer_names_case_sensitive = [
    "AND",
    "THE",
    "ON", 
    "PER",
    "CAN",
    "HIT",
    "LOW",
    "RUN",
    "AIR",
    "TOP",
    "SET",
    "ALL",
    "KEY",
    "MAP",
    "MAX",
    "FAN",
    "ITS",
    "AMP"
]


pii_no_response_message = "Lam Research has a strict policy to ensure the privacy and confidentiality of all customer information, which prevents sharing any customer names or discussing specific customer related issues. Due to a possible match with customer name {}, I am unable to assist you with this query. Please rephrase your query to exclude any customer names, and I will be happy to assist."