from pydantic import BaseModel, Field

class AssistantFile(BaseModel):
    """
    Represents the files managed by the assistant.
    """
    file_name: str = Field(..., description="The name of the file generated by the assistant.")
    file_bytes: bytes = Field(..., description="The byte content of the file generated by the assistant.")